### PR TITLE
Staging -> main merge

### PR DESCRIPTION
**Pull request by johndmulhausen**
Keep this PR open so that CI can run on what we're checking into the staging branch.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!


- Check of `docs/concepts/blockchains.md` came back clean!
- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/content-persistence.md` came back clean!
- Check of `docs/concepts/distributed-web.md` came back clean!
- Check of `docs/concepts/non-fungible-tokens.md` came back clean!
- Check of `docs/how-to/auditing-nfts.md` came back clean!
- Check of `docs/how-to/managing-nfts.md` came back clean!
- Check of `docs/reference/example-apps-code-samples.md` came back clean!
- Check of `docs/reference/featured-sites.md` came back clean!
- Check of `docs/reference/metadata-schemas.md` came back clean!
- Check of `docs/reference/nft-marketplaces.md` came back clean!
- Check of `docs/reference/recommended-tools.md` came back clean!
### `docs/tutorial/end-to-end-experience.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...used for generating content) # With nft.storage # In browser # Manually This...
                                             ^^^^^^^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...uide will walk through interacting with a very simple "hello world" smart co...
                                             ^^^^^^^^^^^^^
  ```
- Reduce redundancy by using “little” or “bit”.
  ```
  ... devnet, but we will still need to do a little bit of setup. # Get some test...
                                             ^^^^^^^^^^
  ```
- Unless you want to emphasize “not”, use “cannot” which is more common.
  ```
  ...hese do not have monetary value as they can not be traded on an exchange, bu...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...guide. scaffold-eth  (opens new window) - a batteries-included starter kit f...
                                             ^
  ```
- Check of `docs/tutorial/gallery-app.md` came back clean!
- Check of `docs/tutorial/minting-app.md` came back clean!
- Check of `docs/tutorial/using-nfts-in-games.md` came back clean!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!


- Check of `docs/concepts/blockchains.md` came back clean!
- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/content-persistence.md` came back clean!
- Check of `docs/concepts/distributed-web.md` came back clean!
### `docs/concepts/non-fungible-tokens.md`:
- Uncountable nouns are usually not used with an indefinite article. Use simply “little background knowledge”.
  ```
  ...understand what an NFT is, we just need a little background knowledge. # A b...
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- If the ‘because’ clause is essential to the meaning, do not use a comma before the clause.
  ```
  ...art, two dollar bills are still fungible, because they each have the same va...
                                             ^^^^^^^^^
  ```
- It is considered good style to insert a comma after introductory phrases with dates or proper nouns.
  ```
  ...the balance of every account, while for Ethereum that shared state is the in...
                                             ^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long there are ...
                                             ^^^^^^^
  ```
- Consider adding a comma.
  ```
  ...n incentivizes its own survival. As long there are people attracted to the e...
                                             ^^^^^^
  ```
- This phrase is redundant. Consider using “Outside”.
  ```
  ...to artists for their digital creations. Outside of digital art and collectib...
                                             ^^^^^^^^^^
  ```
- Check of `docs/how-to/auditing-nfts.md` came back clean!
- Check of `docs/how-to/managing-nfts.md` came back clean!
- Check of `docs/reference/example-apps-code-samples.md` came back clean!
- Check of `docs/reference/featured-sites.md` came back clean!
- Check of `docs/reference/metadata-schemas.md` came back clean!
- Check of `docs/reference/nft-marketplaces.md` came back clean!
- Check of `docs/reference/recommended-tools.md` came back clean!
### `docs/tutorial/end-to-end-experience.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...used for generating content) # With nft.storage # In browser # Manually This...
                                             ^^^^^^^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...uide will walk through interacting with a very simple "hello world" smart co...
                                             ^^^^^^^^^^^^^
  ```
- Reduce redundancy by using “little” or “bit”.
  ```
  ... devnet, but we will still need to do a little bit of setup. # Get some test...
                                             ^^^^^^^^^^
  ```
- Unless you want to emphasize “not”, use “cannot” which is more common.
  ```
  ...hese do not have monetary value as they can not be traded on an exchange, bu...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...guide. scaffold-eth  (opens new window) - a batteries-included starter kit f...
                                             ^
  ```
- Check of `docs/tutorial/gallery-app.md` came back clean!
- Check of `docs/tutorial/minting-app.md` came back clean!
- Check of `docs/tutorial/using-nfts-in-games.md` came back clean!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!


- Check of `docs/concepts/blockchains.md` came back clean!
- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/content-persistence.md` came back clean!
- Check of `docs/concepts/distributed-web.md` came back clean!
### `docs/concepts/non-fungible-tokens.md`:
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long there are ...
                                             ^^^^^^^
  ```
- Consider adding a comma.
  ```
  ...n incentivizes its own survival. As long there are people attracted to the e...
                                             ^^^^^^
  ```
- Check of `docs/how-to/auditing-nfts.md` came back clean!
- Check of `docs/how-to/managing-nfts.md` came back clean!
- Check of `docs/reference/example-apps-code-samples.md` came back clean!
- Check of `docs/reference/featured-sites.md` came back clean!
- Check of `docs/reference/metadata-schemas.md` came back clean!
- Check of `docs/reference/nft-marketplaces.md` came back clean!
- Check of `docs/reference/recommended-tools.md` came back clean!
### `docs/tutorial/end-to-end-experience.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...used for generating content) # With nft.storage # In browser # Manually This...
                                             ^^^^^^^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```
- Check of `docs/tutorial/gallery-app.md` came back clean!
- Check of `docs/tutorial/minting-app.md` came back clean!
- Check of `docs/tutorial/using-nfts-in-games.md` came back clean!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!


- Check of `docs/concepts/blockchains.md` came back clean!
- Check of `docs/concepts/content-addressing.md` came back clean!
- Check of `docs/concepts/content-persistence.md` came back clean!
- Check of `docs/concepts/distributed-web.md` came back clean!
### `docs/concepts/non-fungible-tokens.md`:
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long there are ...
                                             ^^^^^^^
  ```
- Consider adding a comma.
  ```
  ...n incentivizes its own survival. As long there are people attracted to the e...
                                             ^^^^^^
  ```
- Check of `docs/how-to/auditing-nfts.md` came back clean!
- Check of `docs/how-to/creating-nfts.md` came back clean!
- Check of `docs/how-to/managing-nfts.md` came back clean!
- Check of `docs/reference/example-apps-code-samples.md` came back clean!
- Check of `docs/reference/featured-sites.md` came back clean!
- Check of `docs/reference/metadata-schemas.md` came back clean!
- Check of `docs/reference/nft-marketplaces.md` came back clean!
- Check of `docs/reference/recommended-tools.md` came back clean!
- Check of `docs/tutorial/end-to-end-experience.md` came back clean!
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```
- Check of `docs/tutorial/gallery-app.md` came back clean!
- Check of `docs/tutorial/minting-app.md` came back clean!
- Check of `docs/tutorial/using-nfts-in-games.md` came back clean!

**Comment by jessicaschilling** [comment]
Superseded by https://github.com/protocol/nft-website/pull/77.

**Pull request merged**
