### PR TITLE
content: minting app design

### LINKED ISSUE #29: [CONTENT] Building a minting app
This issue is for drafting content for the following:
- Title: Building a minting app
- Address: `/tutorial/minting-app/`

**Contributions are welcome!** If you'd like to make the global NFT developer community better for everyone by creating a guide for this page, please leave a comment and someone from the core team will be in touch ASAP. 🙏

### PR DESCRIPTION
**Pull request by yusefnapora**
This a stab at our new high-level take on "building a minting app", to close #29.

@jessicaschilling this is pretty sparse, but probably better than nothing... I don't really think it's a "tutorial" per-se any more tho, so maybe it should be a "how to" instead? Feel free to move it if you think so :) And of course, tweak anything that needs tweaking.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/tutorial/minting-app.md`:
- As a shorter alternative for ‘able to’, consider using “can”.
  ```
  ...n and control. Today, some applications are able to deliver this, particular...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ens new window), so that users can sign their own transactions using private...
                                             ^^^^^^^^^
  ```
- The word ‘However’ starts a question. Add a question mark (“?”) at the end of the sentence.
  ```
  ...vate keys that never leave their machine. # Testing and infrastructure You w...
                                             ^
  ```
- An apostrophe may be missing.
  ```
  ...indow), it wouldn't be safe to read the users collection of kitties into a J...
                                             ^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...ay want to investigate blockchains like Flow  (opens new window), which was ...
                                             ^^^^
  ```
- This phrase is redundant. Consider writing “evolve”.
  ```
  ...bility Most successful web applications evolve over time, but smart contract...
                                             ^^^^^^^^^^^^^^^^
  ```
- ‘in the long run’ might be wordy. Consider a shorter alternative.
  ```
  ...o upgrade may prove much more expensive in the long run! # User authenticati...
                                             ^^^^^^^^^^^^^^^
  ```
- This expression is usually spelled with a hyphen.
  ```
  ...entials like usernames and passwords. # Wallet based auth It's possible to r...
                                             ^^^^^^^^^^^^
  ```

**Review by jessicaschilling — APPROVED** [review]
@yusefnapora — this is awesome. I see your point about it not quite being a tutorial, but for now at least this seems like the best category; let's leave it for now and reconsider later if need be.

Made a few copy/clarity/corgi edits, and merging!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/tutorial/minting-app.md`:
- Consider a shorter alternative to avoid wordiness.
  ```
  ...'ll take a slightly different approach: In order to help you more holistical...
                                             ^^^^^^^^^^^
  ```
- ‘in the long run’ might be wordy. Consider a shorter alternative.
  ```
  ...g for a platform that won't be relevant in the long run. How easily can new ...
                                             ^^^^^^^^^^^^^^^
  ```
- Use a comma before ‘but’ if it connects two independent clauses (unless they are closely connected and short).
  ```
  ...tform? If a platform is easy to build on but the user experience is less tha...
                                             ^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ens new window), so that users can sign their own transactions using private...
                                             ^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...want to investigate blockchains such as Flow  (opens new window), which was ...
                                             ^^^^
  ```
- This phrase is redundant. Consider writing “created”.
  ```
  ... as Flow  (opens new window), which was originally created to support that v...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- This phrase is redundant. Consider writing “evolve”.
  ```
  ...bility Most successful web applications evolve over time, but smart contract...
                                             ^^^^^^^^^^^^^^^^
  ```
- ‘in the long run’ might be wordy. Consider a shorter alternative.
  ```
  ...o upgrade may prove much more expensive in the long run! # User authenticati...
                                             ^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...can augment or replace traditional user credentials such as usernames and pa...
                                             ^^^^^^^^^^^
  ```
- The phrase ‘do not want to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others.
  ```
  ...uth on Ethereum  (opens new window). If you don't want to deal with writing ...
                                             ^^^^^^^^^^^^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/tutorial/minting-app.md`:
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ens new window), so that users can sign their own transactions using private...
                                             ^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...want to investigate blockchains such as Flow  (opens new window), which was ...
                                             ^^^^
  ```
- This phrase is redundant. Consider writing “created”.
  ```
  ... as Flow  (opens new window), which was originally created to support that v...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- This phrase is redundant. Consider writing “evolve”.
  ```
  ...bility Most successful web applications evolve over time, but smart contract...
                                             ^^^^^^^^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...can augment or replace traditional user credentials such as usernames and pa...
                                             ^^^^^^^^^^^
  ```
- The phrase ‘do not want to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others.
  ```
  ...uth on Ethereum  (opens new window). If you don't want to deal with writing ...
                                             ^^^^^^^^^^^^^^^^^^^^^^
  ```

**Pull request merged**
