### PR TITLE
content: content addressing

### LINKED ISSUE #23: [CONTENT] Content addressing and its benefits for NFTs
This issue is for drafting content for the following:
- Title: Content addressing
- Address: `/concepts/content-addressing/`

The goal is to show how content addressing is the best choice for linking from NFTs to off-chain data.

### Scope

We want to show:

- That NFTs generally contain _links_ to data, not the data itself
- HTTP links are inherently fragile, because they don't identify the data, just its "last known location".
  - Content can change over time, either intentionally or because of change of ownership of the domain, etc
  - If the link dies, it can't be fixed without updating the smart contract state (which might not be possible, depending on the contract)
- IPFS uses hashes / CIDs to identify the data, wherever it comes from
- Since it's an immutable link to the content, it's a great fit for an immutable blockchain record

We can probably link to and / or steal from the [best practices doc on docs.ipfs.io](https://docs.ipfs.io/how-to/best-practices-for-nft-data/)

### PR DESCRIPTION
**Pull request by yusefnapora**
This isn't quite done yet; I still need to shill IPFS a bit 😄. It seems worth checking in though; I feel like I move faster if I push things up as I go instead of waiting until things feel "finished." I should be able to wrap things up this afternoon.

closes #23

### CODE REVIEW

**Comment by yusefnapora** [comment]
It's sweet that github lets you change the base branch after you open a PR now 😄 I always forget to switch to staging...

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!


- Check of `docs/concepts/blockchains.md` came back clean!
### `docs/concepts/content-addressing.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://www.cjr.org/analysis/linkrot-content-drift-new-york-times.php
- This phrase is duplicated. You should probably leave only “Content addressing”.
  ```
  # Content addressing Content addressing is a technique for organizing and locat...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘stores’ seems less likely than ‘stored’.
  ```
  ...nterface is pretty common for key/value stores. Using put, we can associate ...
                                             ^^^^^^
  ```
- Possibly missing preposition found.
  ```
  ...hich keys should be used for which kind data. Things get more complicated wh...
                                             ^^^^
  ```
- Consider using “many”.
  ```
  ...es, or the space needs to be split into many separate "domains" or "name spa...
                                             ^^^^^^^^^^^^^
  ```
- After ‘the’, the verb ‘write’ doesn’t fit. Is ‘write’ spelled correctly? If ‘write’ is the first word in a compound adjective, use a hyphen between the two words. Using the verb ‘write’ as a noun may be non-standard.
  ```
  ...n" in the key space. That mostly solves the write problem - everybody can ma...
                                             ^^^^^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...e. That mostly solves the write problem - everybody can manage their own key...
                                             ^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...he write problem - everybody can manage their own keys without needing to co...
                                             ^^^^^^^^^
  ```
- Consider adding a comma but only if you want to indicate a pause in casual speech.
  ```
  ... clearly this system works pretty well. So what's the problem? The real prob...
                                             ^^
  ```
- ‘in disguise’ might be wordy. Consider a shorter alternative.
  ```
  ...Ts because most NFTs are actually links in disguise. Data storage on most bl...
                                             ^^^^^^^^^^^
  ```
- ‘at the time of’ might be wordy. Consider a shorter alternative.
  ```
  ...), which works out to about $56,000 USD at the time of writing. To make NFTs...
                                             ^^^^^^^^^^^^^^
  ```
- ‘exactly the same’ might be wordy. Consider a shorter alternative.
  ```
  ... The ideal link would always resolve to exactly the same piece of content th...
                                             ^^^^^^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ...n exchange for not being able to choose your own keys, you get some valuable...
                                             ^^^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...vent name collisions. As a consequence, in order to retrieve a value, you ne...
                                             ^^^^^^^^^^^
  ```
- Check of `docs/concepts/content-persistence.md` came back clean!
- Check of `docs/concepts/distributed-web.md` came back clean!
- Check of `docs/concepts/non-fungible-tokens.md` came back clean!
- Check of `docs/how-to/auditing-nfts.md` came back clean!
- Check of `docs/how-to/managing-nfts.md` came back clean!
- Check of `docs/reference/example-apps-code-samples.md` came back clean!
- Check of `docs/reference/featured-sites.md` came back clean!
- Check of `docs/reference/metadata-schemas.md` came back clean!
- Check of `docs/reference/nft-marketplaces.md` came back clean!
- Check of `docs/reference/recommended-tools.md` came back clean!
### `docs/tutorial/end-to-end-experience.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...used for generating content) # With nft.storage # In browser # Manually This...
                                             ^^^^^^^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘very’, consider replacing this phrase.
  ```
  ...uide will walk through interacting with a very simple "hello world" smart co...
                                             ^^^^^^^^^^^^^
  ```
- Reduce redundancy by using “little” or “bit”.
  ```
  ... devnet, but we will still need to do a little bit of setup. # Get some test...
                                             ^^^^^^^^^^
  ```
- Unless you want to emphasize “not”, use “cannot” which is more common.
  ```
  ...hese do not have monetary value as they can not be traded on an exchange, bu...
                                             ^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...guide. scaffold-eth  (opens new window) - a batteries-included starter kit f...
                                             ^
  ```
- Check of `docs/tutorial/gallery-app.md` came back clean!
- Check of `docs/tutorial/minting-app.md` came back clean!
- Check of `docs/tutorial/using-nfts-in-games.md` came back clean!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/content-addressing.md`:
- The following link returned HTTP status code 308 (Permanent Redirect):
  https://nft.storage/login
- This phrase is duplicated. You should probably leave only “Content addressing”.
  ```
  # Content addressing Content addressing is a technique for organizing and locat...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘stores’ seems less likely than ‘stored’.
  ```
  ...nterface is pretty common for key/value stores. Using put, we can associate ...
                                             ^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ... writing problem — everybody can manage their own keys without needing to co...
                                             ^^^^^^^^^
  ```
- ‘in disguise’ might be wordy. Consider a shorter alternative.
  ```
  ...Ts because most NFTs are actually links in disguise. Data storage on most bl...
                                             ^^^^^^^^^^^
  ```
- ‘at the time of’ might be wordy. Consider a shorter alternative.
  ```
  ...), which works out to about $56,000 USD at the time of writing. To make NFTs...
                                             ^^^^^^^^^^^^^^
  ```
- ‘exactly the same’ might be wordy. Consider a shorter alternative.
  ```
  ... The ideal link would always resolve to exactly the same piece of content th...
                                             ^^^^^^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ...n exchange for not being able to choose your own keys, you get some valuable...
                                             ^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...a service from Protocol Labs called nft.storage  (opens new window) to get y...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ural artifacts that NFTs represent, nft.storage provides free storage and ba...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...data. Sign up for a free account at nft.storage  (opens new window) and try ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... try it out! # For more information nft.storage documentation  (opens new wi...
                                             ^^^^^^^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/content-addressing.md`:
- This phrase is duplicated. You should probably leave only “Content addressing”.
  ```
  # Content addressing Content addressing is a technique for organizing and locat...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
- ‘stores’ seems less likely than ‘stored’.
  ```
  ...nterface is pretty common for key/value stores. Using put, we can associate ...
                                             ^^^^^^
  ```
- When specifying a month and year, ‘of’ is unnecessary.
  ```
  ...online storage systems. For example, in May of 2021, the cost to store one m...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ...n exchange for not being able to choose your own keys, you get some valuable...
                                             ^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...a service from Protocol Labs called nft.storage  (opens new window) to get y...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ural artifacts that NFTs represent, nft.storage provides free storage and ba...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...data. Sign up for a free account at nft.storage  (opens new window) and try ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... try it out! # For more information nft.storage documentation  (opens new wi...
                                             ^^^^^^^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```

**Pull request merged**
