### PR TITLE
Create mutable-nfts.md

### PR DESCRIPTION
**Pull request by mishmosh**
This PR creates a new concept guide for Mutable NFTs. Note the bottom section repeats the invitation to contribute from designing a minting app, feel free to remove if redundant.

### CODE REVIEW

**Comment by mishmosh** [comment]
@yusefnapora can you review when you have a chance?

**Review by yusefnapora — APPROVED** [review]
This looks great to me, thanks @mishmosh 👍

I like that we're getting the word out about w3name, and pointing to alternative naming services and Ceramic feel like the right call too.

**Comment by yusefnapora** [comment]
Actually @mishmosh - before you merge this, you may need to add the new file to the config [here](https://github.com/protocol/nft-website/blob/main/docs/.vuepress/config.js#L78), so it shows up in the nav.

**Comment by mishmosh** [comment]
Added the front matter, fingers crossed. I also realized it was not in the correct folder (perhaps another source of ci error), so moved it to `/concepts`.

**Pull request merged**
