### PR TITLE
update e2e tutorial to use new in-browser example app

### PR DESCRIPTION
**Pull request by yusefnapora**
This swaps out Minty for the new hotness, the imaginatively named [NFT School e2e example app](https://github.com/ipfs-shipyard/nft-school-examples/tree/main/end-to-end).

There's one stupid issue with the example app... it's hardcoded to use an nft.storage API token for my account, since that was the fastest way to hack things together. I'll replace that with a `PASTE_YOUR_TOKEN_HERE` placeholder and bring back the instructions for signing up for nft.storage, but it's almost dinner time, so it may be a couple hours :)

Now to find out if Filecorgi has any strong opinions about 3mb animated gifs...

BTW, @jessicaschilling, I hacked up the css a little to make the text legible in dark mode in the "alert box" / tip callouts. I couldn't figure out why it wouldn't let me override the background-color, so I just made the text dark instead so it shows up on the light background.

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/non-fungible-tokens.md`:
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long there are ...
                                             ^^^^^^^
  ```
- Consider adding a comma.
  ```
  ...n incentivizes its own survival. As long there are people attracted to the e...
                                             ^^^^^^
  ```
### `docs/tutorial/end-to-end-experience.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://docs.ethers.io/
- The following link returned HTTP status code 403 (Forbidden):
  https://cointelegraph.com/news/opensea-collector-pulls-the-rug-on-nfts-to-highlight-arbitrary-value
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org
- The following link failed to connect:
  http://localhost:3000
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...oring it on IPFS and Filecoin using nft.storage  (opens new window), all in ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...an Ethereum testnet. # Why IPFS and nft.storage? Our example uses a free ser...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... example uses a free service called nft.storage  (opens new window) to add a...
                                             ^^^^^^^
  ```
- Consider adding a comma here.
  ```
  ...r discussion of content addressing, but for now we'll just give an overview....
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘extremely’, consider replacing this phrase.
  ```
  ...other system, how the data is linked is extremely  important. There are a fe...
                                             ^^^^^^^^^^^^^^^^^^^^
  ```
- Consider using an alternative to avoid wordiness and to strengthen your wording.
  ```
  ...istory. This provides accountability by making it clear to everyone what was...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...s changed, when, and by whom. Using nft.storage, we can make our NFT data av...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tomatically taken care of! Notably, nft.storage includes both long-term "col...
                                             ^^^^^^^
  ```
- Probable usage error. Use “and” after ‘both’.
  ```
  ...d Filecoin  (opens new window) network, as well as "hot storage" using IPFS ...
                                             ^^^^^^^^^^
  ```
- ‘focused’ seems less likely than ‘focuses’.
  ```
  ...no problem. We'll be keeping this guide focused on managing NFT assets and s...
                                             ^^^^^^^
  ```
- Reduce redundancy by using “little” or “bit”.
  ```
  ... with. To mint an NFT, we need to pay a little bit of ETH in gas  (opens new...
                                             ^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...l upload your image and metadata to nft.storage  (opens new window), which w...
                                             ^^^^^^^
  ```
- The phrase ‘feel free to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others and make it sound more professional.
  ```
  ...et into the details of the UI code, but feel free to tinker with it if you w...
                                             ^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... image and metadata onto IPFS using nft.storage  (opens new window). Then we...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... function. # Uploading to IPFS with nft.storage Getting our data into IPFS i...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... into IPFS is simple, thanks to the nft.storage client library  (opens new w...
                                             ^^^^^^^
  ```
- Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
  ```
  ...object returned by the store method has a url property with the IPFS URI for...
                                             ^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/non-fungible-tokens.md`:
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long there are ...
                                             ^^^^^^^
  ```
- Consider adding a comma.
  ```
  ...n incentivizes its own survival. As long there are people attracted to the e...
                                             ^^^^^^
  ```
### `docs/tutorial/end-to-end-experience.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://docs.ethers.io/
- The following link returned HTTP status code 403 (Forbidden):
  https://cointelegraph.com/news/opensea-collector-pulls-the-rug-on-nfts-to-highlight-arbitrary-value
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org
- The following link failed to connect:
  http://localhost:3000
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...oring it on IPFS and Filecoin using nft.storage  (opens new window), all in ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...an Ethereum testnet. # Why IPFS and nft.storage? Our example uses a free ser...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... example uses a free service called nft.storage  (opens new window) to add a...
                                             ^^^^^^^
  ```
- Consider adding a comma here.
  ```
  ...r discussion of content addressing, but for now we'll just give an overview....
                                             ^^^^^^^
  ```
- As an alternative to the over-used intensifier ‘extremely’, consider replacing this phrase.
  ```
  ...other system, how the data is linked is extremely  important. There are a fe...
                                             ^^^^^^^^^^^^^^^^^^^^
  ```
- Consider using an alternative to avoid wordiness and to strengthen your wording.
  ```
  ...istory. This provides accountability by making it clear to everyone what was...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...s changed, when, and by whom. Using nft.storage, we can make our NFT data av...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tomatically taken care of! Notably, nft.storage includes both long-term "col...
                                             ^^^^^^^
  ```
- Probable usage error. Use “and” after ‘both’.
  ```
  ...d Filecoin  (opens new window) network, as well as "hot storage" using IPFS ...
                                             ^^^^^^^^^^
  ```
- ‘focused’ seems less likely than ‘focuses’.
  ```
  ...no problem. We'll be keeping this guide focused on managing NFT assets and s...
                                             ^^^^^^^
  ```
- Reduce redundancy by using “little” or “bit”.
  ```
  ... with. To mint an NFT, we need to pay a little bit of ETH in gas  (opens new...
                                             ^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...l upload your image and metadata to nft.storage  (opens new window), which w...
                                             ^^^^^^^
  ```
- The phrase ‘feel free to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others and make it sound more professional.
  ```
  ...et into the details of the UI code, but feel free to tinker with it if you w...
                                             ^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... image and metadata onto IPFS using nft.storage  (opens new window). Then we...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... function. # Uploading to IPFS with nft.storage Getting our data into IPFS i...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... into IPFS is simple, thanks to the nft.storage client library  (opens new w...
                                             ^^^^^^^
  ```
- Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
  ```
  ...object returned by the store method has a url property with the IPFS URI for...
                                             ^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```

**Review by jessicaschilling — APPROVED** [review]
I made a few commits for ...
- copy edits
- appeasing filecorgi
- fixing dark-mode colors for callout boxes

**@yusefnapora, please merge to main as soon as you get your token stuff fixed!**

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/non-fungible-tokens.md`:
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long as there a...
                                             ^^^^^^^
  ```
### `docs/tutorial/end-to-end-experience.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://docs.ethers.io/
- The following link returned HTTP status code 403 (Forbidden):
  https://cointelegraph.com/news/opensea-collector-pulls-the-rug-on-nfts-to-highlight-arbitrary-value
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...oring it on IPFS and Filecoin using nft.storage  (opens new window), all in ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...an Ethereum testnet. # Why IPFS and nft.storage? Our example uses a free ser...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... example uses a free service called nft.storage  (opens new window) to add a...
                                             ^^^^^^^
  ```
- Consider using an alternative to avoid wordiness and to strengthen your wording.
  ```
  ...istory. This provides accountability by making it clear to everyone what was...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...s changed, when, and by whom. Using nft.storage, we can make our NFT data av...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tomatically taken care of! Notably, nft.storage includes both long-term "col...
                                             ^^^^^^^
  ```
- Probable usage error. Use “and” after ‘both’.
  ```
  ...d Filecoin  (opens new window) network, as well as "hot storage" using IPFS ...
                                             ^^^^^^^^^^
  ```
- ‘focused’ seems less likely than ‘focuses’.
  ```
  ...no problem. We'll be keeping this guide focused on managing NFT assets and s...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...l upload your image and metadata to nft.storage  (opens new window), which w...
                                             ^^^^^^^
  ```
- The phrase ‘feel free to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others and make it sound more professional.
  ```
  ...et into the details of the UI code, but feel free to tinker with it if you w...
                                             ^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... image and metadata onto IPFS using nft.storage  (opens new window). Then we...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... function. # Uploading to IPFS with nft.storage Getting our data into IPFS i...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... into IPFS is simple, thanks to the nft.storage client library  (opens new w...
                                             ^^^^^^^
  ```
- Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
  ```
  ...object returned by the store method has a url property with the IPFS URI for...
                                             ^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/non-fungible-tokens.md`:
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...such a thing as "a single Bitcoin" with its own identity. Whereas cash at le...
                                             ^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “their”.
  ```
  ...ation model allows developers to create their own tokens, which can have spe...
                                             ^^^^^^^^^
  ```
- ‘as a way to’ might be wordy. Consider a shorter alternative.
  ```
  ...le? Earlier we mentioned serial numbers as a way to distinguish one dollar b...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasise that something belongs to a person or thing or was done by a person or thing. Consider writing “its”.
  ```
  ...etwork alive, a blockchain incentivizes its own survival. As long as there a...
                                             ^^^^^^^
  ```
### `docs/tutorial/end-to-end-experience.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://docs.ethers.io/
- The following link returned HTTP status code 403 (Forbidden):
  https://cointelegraph.com/news/opensea-collector-pulls-the-rug-on-nfts-to-highlight-arbitrary-value
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org
- The following link returned HTTP status code 308 (Permanent Redirect):
  https://nft.storage/login
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...oring it on IPFS and Filecoin using nft.storage  (opens new window), all in ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...an Ethereum testnet. # Why IPFS and nft.storage? Our example uses a free ser...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... example uses a free service called nft.storage  (opens new window) to add a...
                                             ^^^^^^^
  ```
- Consider using an alternative to avoid wordiness and to strengthen your wording.
  ```
  ...istory. This provides accountability by making it clear to everyone what was...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...s changed, when, and by whom. Using nft.storage, we can make our NFT data av...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tomatically taken care of! Notably, nft.storage includes both long-term "col...
                                             ^^^^^^^
  ```
- Probable usage error. Use “and” after ‘both’.
  ```
  ...d Filecoin  (opens new window) network, as well as "hot storage" using IPFS ...
                                             ^^^^^^^^^^
  ```
- ‘focused’ seems less likely than ‘focuses’.
  ```
  ...no problem. We'll be keeping this guide focused on managing NFT assets and s...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ens new window). Get an API key for nft.storage To make requests to nft.stor...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...for nft.storage To make requests to nft.storage, you need an API key. Login ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...l upload your image and metadata to nft.storage  (opens new window), which w...
                                             ^^^^^^^
  ```
- The phrase ‘feel free to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others and make it sound more professional.
  ```
  ...et into the details of the UI code, but feel free to tinker with it if you w...
                                             ^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... image and metadata onto IPFS using nft.storage  (opens new window). Then we...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... function. # Uploading to IPFS with nft.storage Getting our data into IPFS i...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... into IPFS is simple, thanks to the nft.storage client library  (opens new w...
                                             ^^^^^^^
  ```
- Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
  ```
  ...object returned by the store method has a url property with the IPFS URI for...
                                             ^
  ```
### `docs/tutorial/first-steps.md`:
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io
- The following link returned HTTP status code 403 (Forbidden):
  https://ropsten.etherscan.io/address/0xE0282e76237B8eB19A5D08e1741b8b3e2691Dadd
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  # First steps Developing apps and experiences for NFTs requires ...
                ^^^^^^^^^^
  ```
- An apostrophe may be missing.
  ```
  ...thers  (opens new window), download the Ethers library as a .js file. For th...
                                             ^^^^^^
  ```
- Possible agreement error.
  ```
  ...ddress detail view  (opens new window). Ethers has a Contract API  (opens ne...
                                             ^^^^^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ...y were regular JavaScript objects named Contract. To wire up a JavaScript ob...
                                             ^^^^^^^^
  ```
- Possible verb agreement error. Did you mean “need”?
  ```
  ...ndow.ethereum object. That's all Ethers needs to provide a Web3 layer for yo...
                                             ^^^^^
  ```
- The genitive (’s) may be missing.
  ```
  ...dity documentation  (opens new window). Ethereum basics  (opens new window) ...
                                             ^^^^^^^^^^^^^^^
  ```

**Pull request merged**
