### PR TITLE
content: replace Minting NFTs how-to with more specific content

### PR DESCRIPTION
**Pull request by jessicaschilling**
As discussed in https://github.com/protocol/nft-website/issues/43, replacing the now-duplicate "Minting NFTs" how-to article with two more specific how-tos:

image

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

- Check of `docs/how-to/lazy-minting.md` came back clean!
- Check of `docs/how-to/minting-on-different-blockchains.md` came back clean!

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!

- Check of `docs/how-to/lazy-minting.md` came back clean!
- Check of `docs/how-to/minting-on-different-blockchains.md` came back clean!

**Comment by jessicaschilling** [comment]
@zebateira, do you have any idea why Fleek might be outputting the preview deploy of this as just a blank directory? Not sure if this looks like a Fleek problem or something else.

**Comment by zebateira** [comment]
@jessicaschilling just confirmed it's a fleek issue. (slack thread for ref: https://protocollabs.slack.com/archives/C013HFZA08L/p1623835439091700)

This affects all websites that are outputting it's build to a path that includes a folder with a `.`. We should halt all deployments for ipfs docs, filecoin docs and ipld.io until this gets fixed from fleek side.

**Comment by zebateira** [comment]
fixed 🚀

**Comment by jessicaschilling** [comment]
Thanks so much @zebateira! Merging now.

**Pull request merged**
