### PR TITLE
ISSUE-32 Recommended tools added

### PR DESCRIPTION
**Pull request by pranshurastogi**
With reference to ISSUE-32, recommended tools README is updated. Suggestions are welcomed !!

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Thanks @pranshurastogi!

@yusefnapora @johndmulhausen - can you please take a look?

**Comment by yusefnapora** [comment]
Beautiful, thanks @pranshurastogi!

**Comment by jessicaschilling** [comment]
Hey @pranshurastogi @yusefnapora -- thanks for the work on this! 😊

Wanted to point out some standards stuff for next time if you don't mind a quick look (@pranshurastogi, we would very much welcome future contributions from you!). If you look at https://github.com/protocol/nft-website/pull/93 you'll see two commits:
- https://github.com/protocol/nft-website/pull/93/commits/710dcd81e0fbb7e9c517f6134ee6cc918fccf14f is an example of the steps to take to remove the "under construction" icon from tab title and left nav, plus replace the "under construction" version of the feedback box with the "was this information helpful" version (this happens programmatically when you remove the `issueURL` from frontmatter and `<ContentStatus />` from page content)
- https://github.com/protocol/nft-website/pull/93/commits/a79863943cbc5425a27489b92663106da3be5921 adds some friendly explanatory context to the top of the page and the section headers, plus presents links in alphabetical order so we don't appear too opinionated

Thanks again!

**Comment by pranshurastogi** [comment]
> Hey @pranshurastogi @yusefnapora -- thanks for the work on this! 
> 
> Wanted to point out some standards stuff for next time if you don't mind a quick look (@pranshurastogi, we would very much welcome future contributions from you!). If you look at #93 you'll see two commits:
> 
> * [710dcd8](https://github.com/protocol/nft-website/commit/710dcd81e0fbb7e9c517f6134ee6cc918fccf14f) is an example of the steps to take to remove the "under construction" icon from tab title and left nav, plus replace the "under construction" version of the feedback box with the "was this information helpful" version (this happens programmatically when you remove the `issueURL` from frontmatter and `<ContentStatus />` from page content)
> * [a798639](https://github.com/protocol/nft-website/commit/a79863943cbc5425a27489b92663106da3be5921) adds some friendly explanatory context to the top of the page and the section headers, plus presents links in alphabetical order so we don't appear too opinionated
> 
> Thanks again!

@jessicaschilling Sure, my bad !! Haven't noticed this while pushing the code, will take care of this in future.

**Pull request merged**
