### PR TITLE
content: add lazy minting guide

### LINKED ISSUE #97: [CONTENT] Lazy minting
This issue is for drafting content for the following:
- Title: Lazy minting
- Address: `/how-to/lazy-minting/`

### PR DESCRIPTION
**Pull request by yusefnapora**
Here's a draft of the lazy minting guide, which closes #97. I went ahead and merged the example into the nft-school-examples repo, so hopefully the links will resolve.

All copy edits and input is welcome 😄

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-to/lazy-minting.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://openzeppelin.org
- A comma may be missing after the conjunctive/linking adverb ‘Otherwise’.
  ```
  ...l probably need some kind of condition. Otherwise anyone who has the voucher...
                                             ^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ction could check to make sure that msg.sender == voucher.recipient. # Creat...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ....recipient. # Creating a signed voucher Using signatures for authorization c...
                                             ^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...rious about the signature verification, check out the contract source  (open...
                                             ^^^^^^^^^
  ```
- Possibly missing comma found.
  ```
  ...12 base contract  (opens new window). # Conclusion Lazy minting is a powerfu...
                                             ^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-to/lazy-minting.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://openzeppelin.org/contracts
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ction could check to make sure that msg.sender == voucher.recipient. # Creat...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ....recipient. # Creating a signed voucher Using signatures for authorization c...
                                             ^^^^^
  ```
- Possibly missing comma found.
  ```
  ...12 base contract  (opens new window). # Conclusion Lazy minting is a powerfu...
                                             ^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-to/lazy-minting.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://openzeppelin.com/contracts
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ction could check to make sure that msg.sender == voucher.recipient. # Creat...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ....recipient. # Creating a signed voucher Using signatures for authorization c...
                                             ^^^^^
  ```
- Possibly missing comma found.
  ```
  ...12 base contract  (opens new window). # Conclusion Lazy minting is a powerfu...
                                             ^^^^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-to/lazy-minting.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ction could check to make sure that msg.sender == voucher.recipient. # Creat...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ....recipient. # Creating a signed voucher Using signatures for authorization c...
                                             ^^^^^
  ```
- Possibly missing comma found.
  ```
  ...12 base contract  (opens new window). # Conclusion Lazy minting is a powerfu...
                                             ^^^^^^^^^^
  ```

**Review by jessicaschilling — APPROVED** [review]
This is super-clear and interesting - thank you! Made a few copy/clarity edits and will merge. @johndmulhausen, please feel free to re-open and make any additional edits you need.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/how-to/lazy-minting.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ction could check to make sure that msg.sender == voucher.recipient. # Creat...
                                             ^^^^^^
  ```
- Only proper nouns start with an uppercase character (there are exceptions for headlines).
  ```
  ....recipient. # Creating a signed voucher Using signatures for authorization c...
                                             ^^^^^
  ```
- Possibly missing comma found.
  ```
  ...12 base contract  (opens new window). # Conclusion Lazy minting is a powerfu...
                                             ^^^^^^^^^^
  ```

**Pull request merged**
