### PR TITLE
add context to metadata schemas page

### LINKED ISSUE #44: [CONTENT] Metadata schemas
This issue is for drafting content for the following:
- Title: Metadata schemas
- Address: `/reference/metadata-schemas/`

**This content is slated for MVP, but might not be included in 20 May round.**

### PR DESCRIPTION
**Pull request by yusefnapora**
This adds an intro paragraph and some more context to the metadata schemas page, plus a link to the "best practices" doc on docs.ipfs.io. I also added a blurb about how nft.storage can handle metadata for you.

Closes #44

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/metadata-schemas.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://ethereum.org
- The following link returned HTTP status code 302 (Found):
  https://binance.org
- Consider a shorter alternative to avoid wordiness.
  ```
  ...example an image, video, or game asset. In order to make an NFT represent so...
                                             ^^^^^^^^^^^
  ```
- Consider a shorter alternative to avoid wordiness.
  ```
  ...display NFTs to buyers and sellers, but in order to do so, the metadata need...
                                             ^^^^^^^^^^^
  ```
- Use ‘own’ only if you want to emphasize that something belongs to a person or thing or was done by a person or thing. Consider writing “your”.
  ```
  ...ta standard, possibly extending it with your own specific needs. This refere...
                                             ^^^^^^^^
  ```
- The verb “check out” can sound colloquial in this context. Consider using a more formal alternative.
  ```
  ...ards. If you have trouble reading them, check out the official JSON Schema g...
                                             ^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ns new window). TIP If you're using nft.storage  (opens new window) to store...
                                             ^^^^^^^
  ```

**Review by jessicaschilling — APPROVED** [review]
Nice intro, thanks so much @yusefnapora! I committed some minor copy/clarity edits, plus appeased the filecorgi on a few matters. I'm going to go ahead and merge this, but @johndmulhausen, please feel free restore the branch to make any additional amends you'd like.

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/metadata-schemas.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://wikipedia.org/wiki/Metadata
- The following link returned HTTP status code 301 (Moved Permanently):
  https://ethereum.org
- The following link returned HTTP status code 302 (Found):
  https://binance.org
- There may an error in the verb form ‘be extend’.
  ```
  ...existing metadata standard, and if need be extend it with your specific need...
                                             ^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ns new window). TIP If you're using nft.storage  (opens new window) to store...
                                             ^^^^^^^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/reference/metadata-schemas.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://wikipedia.org/wiki/Metadata
- The following link returned HTTP status code 301 (Moved Permanently):
  https://ethereum.org
- The following link returned HTTP status code 302 (Found):
  https://binance.org
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ns new window). TIP If you're using nft.storage  (opens new window) to store...
                                             ^^^^^^^
  ```

**Pull request merged**
