### PR TITLE
Content persistence article

### LINKED ISSUE #24: [CONTENT] Content persistence
This issue is for drafting content for the following:
- Title: Content persistence
- Address: `/concepts/content-persistence/`

**This content is slated for MVP, but might not be included in 20 May round.**

This is a potentially tricky one. 

We want to call out that IPFS doesn't give you "persistence" for free; you need to either run your IPFS nodes 24/7 or outsource to a pinning service. We also want to talk about decentralized storage (e.g. Filecoin) and point to nft.storage as an example that is both decentralized and free to use. 

This is working against the common misconception that when you add your data to IPFS, it essentially becomes the network's problem from then on. Since educating people about this is revealing a limitation of IPFS that they might not have been aware of, we should try to steer people to the best and simplest solution for their new problem. For most, that's probably nft.storage, since it's free and makes persistence "someone else's problem", where the "someone else" is Protocol Labs. 

That said, we also need to present alternatives for people that either don't trust our generosity or just want to have more control over their data.

Some questions:

- Why _wouldn't_ you use nft.storage?
  - Hedging your bets on PL's generosity running out?
- Can we point to alternative solutions for people that want to use Filecoin apart from nft.storage? 
  - E.g. Textile Buckets?
- Do we want to link to pinning services? 
  - Which ones?
- Should we link to IPFS cluster docs?

### PR DESCRIPTION
**Pull request by johndmulhausen**
What it says on the tin.

Closes #24

### CODE REVIEW

**Comment by filecorgi** [comment]
- I optimized some images for you! See the commit with the comment `Automatically optimized images [ci skip].` in this PR for details.
- Vuepress build was successful!
### `docs/concepts/content-persistence.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ta. Protocol Labs recently launched nft.storage  (opens new window) to make ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...y store their NFTs. NFTs stored via nft.storage are not only available via t...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...for developers of NFT applications, nft.storage is on the frontlines of that...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tence, exemplified most recently by nft.storage – a solution that demonstrat...
                                             ^^^^^^^
  ```
- Consider using an m-dash if you do not want to join two words.
  ```
  ...xemplified most recently by nft.storage – a solution that demonstrates an el...
                                             ^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/content-persistence.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ta. Protocol Labs recently launched nft.storage  (opens new window) to make ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...y store their NFTs. NFTs stored via nft.storage are not only available via t...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...for developers of NFT applications, nft.storage is on the frontlines of that...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tence, exemplified most recently by nft.storage — a solution that demonstrat...
                                             ^^^^^^^
  ```
### `docs/tutorial/end-to-end-experience.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://docs.ethers.io/
- The following link returned HTTP status code 403 (Forbidden):
  https://cointelegraph.com/news/opensea-collector-pulls-the-rug-on-nfts-to-highlight-arbitrary-value
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org
- The following link returned HTTP status code 308 (Permanent Redirect):
  https://nft.storage/login
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...oring it on IPFS and Filecoin using nft.storage  (opens new window), all in ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...an Ethereum testnet. # Why IPFS and nft.storage? Our example uses a free ser...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... example uses a free service called nft.storage  (opens new window) to add a...
                                             ^^^^^^^
  ```
- Consider using an alternative to avoid wordiness and to strengthen your wording.
  ```
  ...istory. This provides accountability by making it clear to everyone what was...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...s changed, when, and by whom. Using nft.storage, we can make our NFT data av...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tomatically taken care of! Notably, nft.storage includes both long-term "col...
                                             ^^^^^^^
  ```
- Probable usage error. Use “and” after ‘both’.
  ```
  ...d Filecoin  (opens new window) network, as well as "hot storage" using IPFS ...
                                             ^^^^^^^^^^
  ```
- ‘focused’ seems less likely than ‘focuses’.
  ```
  ...no problem. We'll be keeping this guide focused on managing NFT assets and s...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ens new window). Get an API key for nft.storage To make requests to nft.stor...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...for nft.storage To make requests to nft.storage, you need an API key. Login ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...l upload your image and metadata to nft.storage  (opens new window), which w...
                                             ^^^^^^^
  ```
- The phrase ‘feel free to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others and make it sound more professional.
  ```
  ...et into the details of the UI code, but feel free to tinker with it if you w...
                                             ^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... image and metadata onto IPFS using nft.storage  (opens new window). Then we...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... function. # Uploading to IPFS with nft.storage Getting our data into IPFS i...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... into IPFS is simple, thanks to the nft.storage client library  (opens new w...
                                             ^^^^^^^
  ```
- Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
  ```
  ...object returned by the store method has a url property with the IPFS URI for...
                                             ^
  ```

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
### `docs/concepts/content-persistence.md`:
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...FS data. Specific to the NFT space, nft.storage  (opens new window) is a fre...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ogy outlined above, NFTs stored via nft.storage are not only available throu...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...means of ownership and payment. The nft.storage service is one example of th...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...for developers of NFT applications, nft.storage is also encouraging NFT best...
                                             ^^^^^^^
  ```
### `docs/tutorial/end-to-end-experience.md`:
- The following link returned HTTP status code 301 (Moved Permanently):
  https://docs.ethers.io/
- The following link returned HTTP status code 403 (Forbidden):
  https://cointelegraph.com/news/opensea-collector-pulls-the-rug-on-nfts-to-highlight-arbitrary-value
- The following link returned HTTP status code 302 (Found):
  https://nodejs.org
- The following link returned HTTP status code 308 (Permanent Redirect):
  https://nft.storage/login
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...oring it on IPFS and Filecoin using nft.storage  (opens new window), all in ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...an Ethereum testnet. # Why IPFS and nft.storage? Our example uses a free ser...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... example uses a free service called nft.storage  (opens new window) to add a...
                                             ^^^^^^^
  ```
- Consider using an alternative to avoid wordiness and to strengthen your wording.
  ```
  ...istory. This provides accountability by making it clear to everyone what was...
                                             ^^^^^^^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...s changed, when, and by whom. Using nft.storage, we can make our NFT data av...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...tomatically taken care of! Notably, nft.storage includes both long-term "col...
                                             ^^^^^^^
  ```
- Probable usage error. Use “and” after ‘both’.
  ```
  ...d Filecoin  (opens new window) network, as well as "hot storage" using IPFS ...
                                             ^^^^^^^^^^
  ```
- ‘focused’ seems less likely than ‘focuses’.
  ```
  ...no problem. We'll be keeping this guide focused on managing NFT assets and s...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...ens new window). Get an API key for nft.storage To make requests to nft.stor...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...for nft.storage To make requests to nft.storage, you need an API key. Login ...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ...l upload your image and metadata to nft.storage  (opens new window), which w...
                                             ^^^^^^^
  ```
- The phrase ‘feel free to’ is used quite frequently. Consider using a less frequent alternative to set your writing apart from others and make it sound more professional.
  ```
  ...et into the details of the UI code, but feel free to tinker with it if you w...
                                             ^^^^^^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... image and metadata onto IPFS using nft.storage  (opens new window). Then we...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... function. # Uploading to IPFS with nft.storage Getting our data into IPFS i...
                                             ^^^^^^^
  ```
- If a new sentence starts here, add a space and start with an uppercase letter.
  ```
  ... into IPFS is simple, thanks to the nft.storage client library  (opens new w...
                                             ^^^^^^^
  ```
- Use “an” instead of ‘a’ if the following word starts with a vowel sound, e.g. ‘an article’, ‘an hour’.
  ```
  ...object returned by the store method has a url property with the IPFS URI for...
                                             ^
  ```

**Review by jessicaschilling — APPROVED** [review]
- Rearranged image locations to bring us into line with our standards
- Copy and clarity edits
- Some content edits to make more apropos to NFT School, since original content source was PL/Filecoin blog and thus assumes some internal knowledge/alignment

**Comment by jessicaschilling** [comment]
@yusefnapora and/or @johndmulhausen -- please feel free to merge when you're ready!

**Comment by yusefnapora** [comment]
@johndmulhausen & @jessicaschilling nice work 💯

**Pull request merged**
