### PR TITLE
feat: add algolia config

### LINKED ISSUE #61: Add Algolia search once approved for open-source use
Splitting this out in its own issue from https://github.com/protocol/nft-website/issues/22 for post-MVP work.

Looks unlikely that Algolia will approve this site for an open-source license until MVP is launched and the URL has more public content. @zebateira — can you please re-submit to Algolia once the site is soft-launched with DNS correctly pointed? Thank you!

### PR DESCRIPTION
**Pull request by zebateira**
Closes #61

### CODE REVIEW

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by zebateira** [comment]
Just going to try and fix that green.

Screenshot 2021-06-08 at 12 07 41 PM

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Comment by zebateira** [comment]
@jessicaschilling styles fixed for the algolia search. let me know what you think!

**Review by jessicaschilling — APPROVED** [review]
Nice! Mind making the link text the same purple as in the body content? Then please put it on a boat! 😊 

image

**Comment by filecorgi** [comment]
- Image optimization came back clean!
- Vuepress build was successful!
- No markdown files were changed, so no page checks were run!

**Pull request merged**
